### ISSUE TITLE
Could you provide the prompt for Vicuna?

### ISSUE THREAD

**Issue by LinB203** [Enderfga/FineRewards#2]
If I have some labels from Ground-SAM, such as apple, banana and so on. How should I ask Vicuna to get the result?

**Comment by Enderfga** [comment]
![image](https://github.com/Enderfga/FineRewards/assets/74981769/8a9ed370-de18-4638-843b-ad9ef0ea5653)
The calculation method is shown in the figure, and the specific prompts used are already provided in the code.

**Comment by LinB203** [comment]
> ![image](https://user-images.githubusercontent.com/74981769/252561539-8a9ed370-de18-4638-843b-ad9ef0ea5653.png) The calculation method is shown in the figure, and the specific prompts used are already provided in the code.

thanks for your patient reply.
